"""
================================================================================
 ROBOT CONTROL DASHBOARD (GUI)
================================================================================
Pure-Python GUI (Tkinter only, no external dependencies) meant to run on a
laptop / touchscreen / the Raspberry Pi 5 itself, and act as the "face" of
your robot.

WHAT THIS FILE IS RIGHT NOW
----------------------------
This is a VISUAL MOCKUP. Every number you see (battery %, memory, cpu,
connectivity, current activity) is randomly generated by the `RobotCore`
class below so you can see exactly how the dashboard behaves in real time
(the values change every couple of seconds, a live feed scrolls, etc.)
without anything actually being wired to hardware yet.

HOW THIS WILL LATER CONNECT TO THE REAL RASPBERRY PI 5
-------------------------------------------------------
All "fake" data comes from ONE place: the `RobotCore` class. Every method in
it is tagged with a "TODO(connect)" comment. When you tell me to wire this
up for real, I will only need to touch that class (e.g. open a socket /
MQTT client / REST session to the Pi, or read GPIO / battery HAT values
directly if this GUI runs on the Pi itself) -- the rest of the GUI already
knows how to display whatever that class returns, so nothing else needs to
change. That's the whole point of keeping RobotCore separate.

Suggested (not yet implemented) connection options for later:
    1. Run a small Flask/FastAPI server on the Pi that exposes /status,
       /connect, /register_owner endpoints -> GUI polls it over HTTP.
    2. Run an MQTT broker on the Pi (or elsewhere) -> GUI subscribes to
       topics like robot/battery, robot/activity, robot/memory.
    3. A raw TCP/WebSocket connection with a simple JSON protocol.
    4. If the GUI runs directly on the Pi: read psutil / vcgencmd /
       battery-HAT I2C registers directly, no network needed at all.

Just tell me which of these (or something else) you want, and I will
implement it inside RobotCore without touching the rest of the file.

REQUIREMENTS
------------
Nothing but the Python standard library (tkinter, which ships with Python).
On Raspberry Pi OS, if tkinter isn't already installed:
    sudo apt-get install python3-tk

RUN
---
    python3 gui.py
================================================================================
"""

import tkinter as tk
from tkinter import ttk, messagebox
import random
import datetime
import math
import os
import json
import threading
import wave

try:
    import audioop  # stdlib; used only to draw a real waveform preview
    AUDIOOP_AVAILABLE = True
except ImportError:
    AUDIOOP_AVAILABLE = False

# -- real hardware capture modules (kept in their own files on purpose) ----
# face_capture.py  -> talks to the webcam (needs opencv-python)
# voice_capture.py -> talks to the microphone (needs pyaudio)
# Both are optional at import time so the GUI still opens even if a
# dependency isn't installed yet; the relevant button will just explain
# what to install.
try:
    import face_capture
    FACE_MODULE_ERROR = None
except ImportError as e:
    face_capture = None
    FACE_MODULE_ERROR = str(e)

try:
    import voice_capture
    VOICE_MODULE_ERROR = None
except ImportError as e:
    voice_capture = None
    VOICE_MODULE_ERROR = str(e)

# -- real Pluto communication modules (Software/ side) ----------------------
# api_client.py       -> FastAPI REST calls, Software -> Pluto (commands,
#                        owner registration, memory reads)
# websocket_client.py -> persistent WebSocket, Pluto -> Software (telemetry)
# video_client.py      -> persistent WebSocket, Pluto -> Software (camera feed)
# Imports are wrapped so the GUI still opens even if `websocket-client` /
# `pillow` aren't installed yet; the Connect button will just explain why.
try:
    from api_client import PlutoAPIClient, PlutoAPIClientError
    API_CLIENT_ERROR = None
except ImportError as e:
    PlutoAPIClient = None
    PlutoAPIClientError = Exception
    API_CLIENT_ERROR = str(e)

try:
    from websocket_client import PlutoWebSocketClient
    WS_CLIENT_ERROR = None
except ImportError as e:
    PlutoWebSocketClient = None
    WS_CLIENT_ERROR = str(e)

try:
    from video_client import PlutoVideoClient
    from PIL import ImageTk
    VIDEO_CLIENT_ERROR = None
except ImportError as e:
    PlutoVideoClient = None
    ImageTk = None
    VIDEO_CLIENT_ERROR = str(e)

# ------------------------------------------------------------------------
# Connection settings -- Pluto's Raspberry Pi 5 address and the two service
# ports: FastAPI (Software -> Pluto commands/registration) and WebSocket
# (Pluto -> Software live telemetry + camera stream).
# ------------------------------------------------------------------------
ROBOT_HOST = "100.103.110.54"   # Pi's hostname / IP
ROBOT_API_PORT = 8000              # FastAPI server (server.py)
ROBOT_WS_PORT = 8000               # websocket_server.py / camera_stream.py / telemetry.py
                                    # are all mounted onto the SAME FastAPI app as
                                    # server.py, so they share port 8000 -- there is
                                    # no separate WS service on a different port.
TELEMETRY_ENDPOINT = "/ws/telemetry"
CAMERA_ENDPOINT = "/ws/camera"

# ------------------------------------------------------------------------
# NOTE: owner records are NOT persisted locally anymore. Pluto's own
# pluto.db (via server.py's /owners endpoints) is the single source of
# truth for registered owners -- see OwnerRegistrationFrame below, which
# reads the table from GET /owners after every successful registration
# instead of keeping a parallel captured_data/owners.json file.
# ------------------------------------------------------------------------


def _to_iso_dob(dob_str):
    """
    Converts the GUI's 'DD-MM-YYYY' dob string (built from the day/month/year
    comboboxes in OwnerRegistrationFrame) into the 'YYYY-MM-DD' format
    owner_manager.py's validation expects. Returns "" if it can't be parsed
    (owner_manager treats an empty dob as optional).
    """
    try:
        day, month, year = dob_str.split("-")
        return f"{year}-{int(month):02d}-{int(day):02d}"
    except (ValueError, AttributeError):
        return ""


# ============================================================================
#  ROBOT CORE  (mock backend -- the ONLY place that needs to change later)
# ============================================================================
class RobotCore:
    """
    Real interface between the GUI and Pluto (Raspberry Pi 5).

    - api_client.PlutoAPIClient   : FastAPI REST calls (Software -> Pluto):
                                    owner registration, memory reads, commands.
    - websocket_client...Client   : persistent WebSocket (Pluto -> Software):
                                    telemetry (battery/cpu/ram/temp/env/activity).
    - video_client.PlutoVideoClient: persistent WebSocket (Pluto -> Software):
                                    live camera frames.

    All getters below read from a locally cached snapshot that is updated
    by the WebSocket callbacks in the background. Until Pluto is reachable,
    getters return safe "no data yet" placeholders instead of random values.
    """

    # Default snapshot before any telemetry has arrived / while offline.
    _EMPTY_TELEMETRY = {
        "battery_percent": None,
        "connectivity": {"type": "Offline", "state": "No Signal", "kind": "bad"},
        "memory_percent": None,
        "cpu_percent": None,
        "cpu_temp_c": None,
        "ambient_temperature_c": None,
        "humidity_percent": None,
        "light_intensity_lux": None,
        "air_quality_index": None,
        "current_activity": "Disconnected",
    }

    _EMPTY_MEMORY_CARD = {
        "title": "", "short_desc": "No data \u2014 connect to Pluto to load this.",
        "purpose": "", "used_mb": 0, "total_mb": 0, "entries": [],
    }

    def __init__(self):
        self.connected = False
        self.host = ROBOT_HOST
        self.api_port = ROBOT_API_PORT
        self.ws_port = ROBOT_WS_PORT

        self._telemetry_lock = threading.Lock()
        self._telemetry = dict(self._EMPTY_TELEMETRY)

        self._frame_lock = threading.Lock()
        self._latest_frame = None  # PIL.Image or None

        self.api = PlutoAPIClient(host=self.host, port=self.api_port) if PlutoAPIClient else None
        self.telemetry_client = None
        self.video_client = None

    # -- connection lifecycle -------------------------------------------------
    def connect(self):
        """
        Verifies Pluto's FastAPI server is reachable, then starts the
        telemetry and camera WebSocket clients. Returns True only if the
        REST health check succeeds; the WS clients keep retrying in the
        background regardless (they'll pick up automatically once Pluto is
        actually online), so this call never blocks on them.
        """
        if self.api is None:
            return False

        try:
            self.connected = self.api.health_check()
        except PlutoAPIClientError:
            self.connected = False

        if PlutoWebSocketClient and self.telemetry_client is None:
            self.telemetry_client = PlutoWebSocketClient(
                host=self.host, port=self.ws_port, endpoint=TELEMETRY_ENDPOINT,
                on_message=self._on_telemetry_message,
                on_connect=lambda: setattr(self, "connected", True),
                on_disconnect=self._on_telemetry_disconnect,
            )
            self.telemetry_client.start()

        if PlutoVideoClient and self.video_client is None:
            self.video_client = PlutoVideoClient(
                host=self.host, port=self.ws_port, endpoint=CAMERA_ENDPOINT,
                on_frame=self._on_video_frame,
            )
            self.video_client.start()

        return self.connected

    def disconnect(self):
        if self.telemetry_client:
            self.telemetry_client.stop()
        if self.video_client:
            self.video_client.stop()
        if self.api:
            self.api.close()
        self.connected = False
        with self._telemetry_lock:
            self._telemetry = dict(self._EMPTY_TELEMETRY)
        with self._frame_lock:
            self._latest_frame = None

    # -- WebSocket callbacks (run on background threads) ---------------------
    def _on_telemetry_message(self, data: dict):
        """
        telemetry.py (Pi side) sends: cpu_percent, ram_percent, ram_used_mb,
        ram_total_mb, disk_percent, temperature_c, battery_percent,
        battery_charging, uptime_seconds.

        RobotCore's getters (below) were written against different key
        names (memory_percent, cpu_temp_c, connectivity, current_activity)
        and against environment-sensor fields telemetry.py doesn't send at
        all (those live in STM's sensor rows, pushed separately over
        websocket_server.py's /ws/live -- not this channel). Translate here
        so the rest of RobotCore doesn't need to change.
        """
        translated = {
            "cpu_percent": data.get("cpu_percent"),
            "memory_percent": data.get("ram_percent"),
            "cpu_temp_c": data.get("temperature_c"),
            "battery_percent": data.get("battery_percent"),
            "connectivity": {
                "type": "Connected", "state": "Online", "kind": "good",
            },
            "current_activity": data.get("current_activity", "Idle"),
        }
        with self._telemetry_lock:
            self._telemetry.update(translated)

    def _on_telemetry_disconnect(self):
        self.connected = False
        with self._telemetry_lock:
            self._telemetry["connectivity"] = {
                "type": "Offline", "state": "No Signal", "kind": "bad",
            }

    def _on_video_frame(self, image):
        with self._frame_lock:
            self._latest_frame = image

    def get_latest_frame(self):
        """Returns the most recent camera frame (PIL.Image) or None."""
        with self._frame_lock:
            return self._latest_frame

    # -- telemetry getters (read from the cached WebSocket snapshot) ---------
    def _snapshot(self):
        with self._telemetry_lock:
            return dict(self._telemetry)

    def get_battery_percent(self):
        val = self._snapshot().get("battery_percent")
        return val if val is not None else 0

    def get_connectivity(self):
        c = self._snapshot().get("connectivity") or self._EMPTY_TELEMETRY["connectivity"]
        return c.get("type", "Offline"), c.get("state", "No Signal"), c.get("kind", "bad")

    def get_memory_percent(self):
        val = self._snapshot().get("memory_percent")
        return val if val is not None else 0

    def get_cpu_percent(self):
        val = self._snapshot().get("cpu_percent")
        return val if val is not None else 0

    def get_cpu_temp_c(self):
        val = self._snapshot().get("cpu_temp_c")
        return val if val is not None else 0

    # -- environment / surrounding sensors -----------------------------------
    def get_ambient_temperature_c(self):
        val = self._snapshot().get("ambient_temperature_c")
        return val if val is not None else "--"

    def get_humidity_percent(self):
        val = self._snapshot().get("humidity_percent")
        return val if val is not None else "--"

    def get_light_intensity_lux(self):
        val = self._snapshot().get("light_intensity_lux")
        return val if val is not None else "--"

    def get_air_quality_index(self):
        val = self._snapshot().get("air_quality_index")
        return val if val is not None else 0

    def get_live_feed_status(self):
        return bool(self.video_client and self.video_client.is_connected())

    def get_current_activity(self):
        return self._snapshot().get("current_activity") or "Disconnected"

    # -- MEMORY CORE ----------------------------------------------------------
    # Four memory subsystems, read live from Pluto over the FastAPI
    # /memory/{type}/summary endpoint (see api_client.get_memory_summary).
    def get_memory_core_data(self):
        types = ("short_term", "semantic", "behavioral", "episodic")
        result = {}
        for t in types:
            if not self.api:
                result[t] = dict(self._EMPTY_MEMORY_CARD)
                continue
            try:
                result[t] = self.api.get_memory_summary(t)
            except PlutoAPIClientError:
                result[t] = dict(self._EMPTY_MEMORY_CARD)
        return result

    def register_owner(self, owner_data):
        """
        Sends the owner's face/voice samples to Pluto for enrollment via
        the FastAPI server (owner_manager.py). Returns True on success,
        False (and leaves the caller to inspect self.last_error) otherwise.

        server.py's /owners/register endpoint (owner_manager.py) requires
        AT LEAST ONE face file AND one voice file in the SAME call -- so
        both must be captured before this is invoked (see save_owner()'s
        validation in OwnerRegistrationFrame).
        """
        if not self.api:
            self.last_error = "API client unavailable (install 'requests')."
            return False

        name = owner_data.get("name", "owner")

        if not (owner_data.get("face_captured") and owner_data.get("face_path")):
            self.last_error = "A face capture is required to register an owner."
            return False
        if not (owner_data.get("voice_captured") and owner_data.get("voice_path")):
            self.last_error = "A voice sample is required to register an owner."
            return False

        # owner_manager.py validates dob strictly as 'YYYY-MM-DD'; the GUI's
        # date pickers build 'DD-MM-YYYY', so convert before sending.
        dob = _to_iso_dob(owner_data.get("dob", ""))

        try:
            self.api.register_owner(
                owner_name=name,
                dob=dob,
                face_paths=[owner_data["face_path"]],
                voice_paths=[owner_data["voice_path"]],
            )
            self.last_error = None
            return True
        except PlutoAPIClientError as e:
            self.last_error = str(e)
            return False


# ============================================================================
#  THEME
# ============================================================================
class Theme:
    BG = "#0a0e14"          # app background
    BG_SIDEBAR = "#0d1219"
    CARD = "#131a24"
    CARD_SHADOW = "#060809"
    BORDER = "#1f2733"
    TRACK = "#1b232f"

    ACCENT = "#22e3c8"      # primary cyan-teal
    ACCENT_2 = "#7c6bff"    # secondary violet (used for gradients / highlights)
    ACCENT_DIM = "#0f2b28"

    TEXT_MAIN = "#eef2f6"
    TEXT_SUB = "#7c8a99"
    TEXT_FAINT = "#4d5a68"

    GOOD = "#2fe88f"
    WARN = "#ffb648"
    BAD = "#ff5c72"

    FONT = "Segoe UI" if False else "Helvetica"  # safe cross-platform default


def status_color(kind):
    return {"good": Theme.GOOD, "warn": Theme.WARN, "bad": Theme.BAD}.get(kind, Theme.TEXT_SUB)


def level_color(value, invert=False):
    """value 0-100 -> color. invert=True means 'high value is bad' (e.g. usage)."""
    if invert:
        if value >= 80:
            return Theme.BAD
        if value >= 55:
            return Theme.WARN
        return Theme.GOOD
    else:
        if value <= 20:
            return Theme.BAD
        if value <= 45:
            return Theme.WARN
        return Theme.GOOD


def mix(hex1, hex2, t):
    """Linearly blend two hex colors, t in [0,1]."""
    r1, g1, b1 = int(hex1[1:3], 16), int(hex1[3:5], 16), int(hex1[5:7], 16)
    r2, g2, b2 = int(hex2[1:3], 16), int(hex2[3:5], 16), int(hex2[5:7], 16)
    r = round(r1 + (r2 - r1) * t)
    g = round(g1 + (g2 - g1) * t)
    b = round(b1 + (b2 - b1) * t)
    return f"#{r:02x}{g:02x}{b:02x}"


# ============================================================================
#  LOW-LEVEL DRAWING HELPERS (rounded rects + vector icons)
# ============================================================================
def rounded_rect_points(x1, y1, x2, y2, r):
    r = min(r, (x2 - x1) / 2, (y2 - y1) / 2)
    return [
        x1 + r, y1, x2 - r, y1, x2, y1, x2, y1 + r,
        x2, y2 - r, x2, y2, x2 - r, y2, x1 + r, y2,
        x1, y2, x1, y2 - r, x1, y1 + r, x1, y1,
    ]


def draw_rounded_rect(canvas, x1, y1, x2, y2, r=14, **kwargs):
    return canvas.create_polygon(rounded_rect_points(x1, y1, x2, y2, r), smooth=True, **kwargs)


def draw_gradient_strip(canvas, x1, y1, x2, y2, c1, c2, steps=60):
    width = (x2 - x1) / steps
    for i in range(steps):
        t = i / (steps - 1)
        color = mix(c1, c2, t)
        canvas.create_rectangle(x1 + i * width, y1, x1 + (i + 1) * width + 1, y2,
                                 fill=color, outline=color)


def icon_battery(canvas, cx, cy, s, color):
    w, h = s, s * 0.55
    x0, y0 = cx - w / 2, cy - h / 2
    canvas.create_rectangle(x0, y0, x0 + w * 0.86, y0 + h, outline=color, width=2)
    canvas.create_rectangle(x0 + w * 0.86, y0 + h * 0.25, x0 + w, y0 + h * 0.75,
                             fill=color, outline=color)
    canvas.create_rectangle(x0 + 3, y0 + 3, x0 + w * 0.55, y0 + h - 3, fill=color, outline="")


def icon_signal(canvas, cx, cy, s, color, dim):
    bars = 4
    base_y = cy + s * 0.4
    bw = s * 0.16
    gap = s * 0.08
    total_w = bars * bw + (bars - 1) * gap
    x = cx - total_w / 2
    for i in range(bars):
        h = s * 0.22 * (i + 1)
        col = color if i < 3 else dim
        canvas.create_rectangle(x, base_y - h, x + bw, base_y, fill=col, outline="")
        x += bw + gap


def icon_chip(canvas, cx, cy, s, color):
    w = s * 0.62
    x0, y0 = cx - w / 2, cy - w / 2
    canvas.create_rectangle(x0, y0, x0 + w, y0 + w, outline=color, width=2)
    canvas.create_rectangle(x0 + w * 0.28, y0 + w * 0.28, x0 + w * 0.72, y0 + w * 0.72,
                             outline=color, width=1.5)
    pins = 3
    step = w / (pins + 1)
    for i in range(1, pins + 1):
        px = x0 + i * step
        canvas.create_line(px, y0, px, y0 - s * 0.12, fill=color, width=2)
        canvas.create_line(px, y0 + w, px, y0 + w + s * 0.12, fill=color, width=2)
        py = y0 + i * step
        canvas.create_line(x0, py, x0 - s * 0.12, py, fill=color, width=2)
        canvas.create_line(x0 + w, py, x0 + w + s * 0.12, py, fill=color, width=2)


def icon_cpu(canvas, cx, cy, s, color):
    r = s * 0.32
    canvas.create_oval(cx - r, cy - r, cx + r, cy + r, outline=color, width=2)
    canvas.create_arc(cx - r * 0.5, cy - r * 0.5, cx + r * 0.5, cy + r * 0.5,
                       start=20, extent=180, style="arc", outline=color, width=2)


def icon_robot_head(canvas, cx, cy, s, color):
    w, h = s * 0.9, s * 0.75
    draw_rounded_rect(canvas, cx - w / 2, cy - h / 2, cx + w / 2, cy + h / 2,
                       r=s * 0.16, outline=color, width=2, fill="")
    eye_r = s * 0.08
    canvas.create_oval(cx - w * 0.22 - eye_r, cy - eye_r, cx - w * 0.22 + eye_r, cy + eye_r,
                        fill=color, outline="")
    canvas.create_oval(cx + w * 0.22 - eye_r, cy - eye_r, cx + w * 0.22 + eye_r, cy + eye_r,
                        fill=color, outline="")
    canvas.create_line(cx, cy - h / 2, cx, cy - h / 2 - s * 0.14, fill=color, width=2)
    canvas.create_oval(cx - 2.5, cy - h / 2 - s * 0.14 - 2.5, cx + 2.5, cy - h / 2 - s * 0.14 + 2.5,
                        fill=color, outline="")


def icon_person(canvas, cx, cy, s, color):
    r = s * 0.24
    canvas.create_oval(cx - r, cy - r * 1.5, cx + r, cy + r * 0.5, outline=color, width=2)
    canvas.create_arc(cx - r * 1.5, cy + r * 0.1, cx + r * 1.5, cy + r * 2.6,
                       start=20, extent=140, style="arc", outline=color, width=2)


def icon_mic(canvas, cx, cy, s, color):
    w, h = s * 0.28, s * 0.5
    draw_rounded_rect(canvas, cx - w / 2, cy - h / 2, cx + w / 2, cy + h / 2,
                       r=w / 2, outline=color, width=2, fill="")
    canvas.create_arc(cx - w, cy - h * 0.1, cx + w, cy + h * 0.9, start=200, extent=140,
                       style="arc", outline=color, width=2)
    canvas.create_line(cx, cy + h * 0.45, cx, cy + h * 0.75, fill=color, width=2)
    canvas.create_line(cx - w * 0.7, cy + h * 0.75, cx + w * 0.7, cy + h * 0.75,
                        fill=color, width=2)


def icon_bolt(canvas, cx, cy, s, color):
    pts = [cx - s * 0.08, cy - s * 0.32, cx + s * 0.18, cy - s * 0.32, cx - s * 0.02, cy,
            cx + s * 0.14, cy, cx - s * 0.18, cy + s * 0.32, cx - s * 0.06, cy + s * 0.02,
            cx - s * 0.2, cy + s * 0.02]
    canvas.create_polygon(pts, fill=color, outline="")


# ============================================================================
#  ROUNDED CARD CONTAINER
# ============================================================================
class RoundedCard(tk.Frame):
    """A card with a soft shadow and rounded corners, hosting an inner
    tk.Frame (self.body) where real content should be packed/gridded."""

    def __init__(self, parent, radius=16, bg=Theme.CARD, border=Theme.BORDER, pad=0,
                 width=None, height=None):
        super().__init__(parent, bg=parent["bg"])
        self.radius = radius
        self.card_bg = bg
        self.border = border
        canvas_kwargs = {}
        if width is not None:
            canvas_kwargs["width"] = width
        if height is not None:
            canvas_kwargs["height"] = height
        self.canvas = tk.Canvas(self, bg=parent["bg"], highlightthickness=0, bd=0, **canvas_kwargs)
        self.canvas.pack(fill="both", expand=True)
        self.body = tk.Frame(self.canvas, bg=bg)
        self._win = self.canvas.create_window(4, 4, window=self.body, anchor="nw")
        self.canvas.bind("<Configure>", self._redraw)

    def _redraw(self, event):
        w, h = event.width, event.height
        self.canvas.delete("bg")
        # soft shadow (offset, darker)
        draw_rounded_rect(self.canvas, 3, 5, w - 1, h - 1, self.radius,
                           fill=Theme.CARD_SHADOW, outline="", tags="bg")
        # main card
        draw_rounded_rect(self.canvas, 0, 0, w - 4, h - 4, self.radius,
                           fill=self.card_bg, outline=self.border, width=1, tags="bg")
        self.canvas.tag_lower("bg")
        self.canvas.itemconfig(self._win, width=w - 12, height=h - 14)
        self.canvas.coords(self._win, 6, 6)


# ============================================================================
#  RADIAL GAUGE STAT CARD
# ============================================================================
class GaugeCard(RoundedCard):
    def __init__(self, parent, icon_fn, title):
        super().__init__(parent)
        self.icon_fn = icon_fn

        header = tk.Frame(self.body, bg=Theme.CARD)
        header.pack(fill="x", padx=16, pady=(14, 0))
        self.icon_canvas = tk.Canvas(header, width=22, height=22, bg=Theme.CARD,
                                      highlightthickness=0)
        self.icon_canvas.pack(side="left")
        tk.Label(header, text=title, font=(Theme.FONT, 10, "bold"), bg=Theme.CARD,
                 fg=Theme.TEXT_SUB).pack(side="left", padx=(8, 0))

        self.gauge = tk.Canvas(self.body, width=128, height=128, bg=Theme.CARD,
                                highlightthickness=0)
        self.gauge.pack(pady=(6, 2))

        self.footer_label = tk.Label(self.body, text="", font=(Theme.FONT, 9),
                                      bg=Theme.CARD, fg=Theme.TEXT_SUB)
        self.footer_label.pack(pady=(0, 14))

        self._draw_icon(Theme.ACCENT)

    def _draw_icon(self, color):
        self.icon_canvas.delete("all")
        self.icon_fn(self.icon_canvas, 11, 11, 20, color)

    def set_value(self, percent, center_text, sub_text, footer_text, color):
        self._draw_icon(color)
        g = self.gauge
        g.delete("all")
        size = 128
        cx = cy = size / 2
        r = size / 2 - 10
        width = 10
        g.create_oval(cx - r, cy - r, cx + r, cy + r, outline=Theme.TRACK, width=width)
        extent = -3.6 * max(0, min(100, percent))
        if percent > 0:
            # draw arc in small steps to fake rounded look isn't necessary; single arc is fine
            g.create_arc(cx - r, cy - r, cx + r, cy + r, start=90, extent=extent,
                         style="arc", outline=color, width=width)
        g.create_text(cx, cy - 6, text=center_text, fill=Theme.TEXT_MAIN,
                      font=(Theme.FONT, 19, "bold"))
        g.create_text(cx, cy + 16, text=sub_text, fill=Theme.TEXT_SUB,
                      font=(Theme.FONT, 8, "bold"))
        self.footer_label.config(text=footer_text)


# ============================================================================
#  COMPACT STAT CARD (small top-strip status boxes)
# ============================================================================
class MiniStatCard(RoundedCard):

    def __init__(self, parent, icon_fn, title):
        super().__init__(parent, radius=12, height=78)

        self.icon_fn = icon_fn

        row = tk.Frame(self.body, bg=Theme.CARD)
        row.pack(fill="both", expand=True, padx=14, pady=10)

        row.columnconfigure(1, weight=1)

        self.icon_canvas = tk.Canvas(
            row,
            width=22,
            height=22,
            bg=Theme.CARD,
            highlightthickness=0
        )
        self.icon_canvas.grid(
            row=0,
            column=0,
            rowspan=3,
            sticky="nw",
            padx=(0,10)
        )

        tk.Label(
            row,
            text=title,
            font=(Theme.FONT,8,"bold"),
            bg=Theme.CARD,
            fg=Theme.TEXT_SUB
        ).grid(row=0,column=1,sticky="w")

        self.value_label = tk.Label(
            row,
            text="--",
            font=(Theme.FONT,16,"bold"),
            bg=Theme.CARD,
            fg=Theme.TEXT_MAIN
        )
        self.value_label.grid(row=1,column=1,sticky="w")

        self.sub_label = tk.Label(
            row,
            text="",
            font=(Theme.FONT,8),
            bg=Theme.CARD,
            fg=Theme.TEXT_FAINT
        )
        self.sub_label.grid(row=2,column=1,sticky="w")

    def _draw_icon(self, color):
        self.icon_canvas.delete("all")
        self.icon_fn(self.icon_canvas, 11, 11, 18, color)

    def set_value(self, value_text, sub_text, color):
        self._draw_icon(color)
        self.value_label.config(text=value_text, fg=color)
        self.sub_label.config(text=sub_text)

        self._draw_icon(Theme.ACCENT)


# ============================================================================
#  LIVE MONITOR CARD (placeholder for Pluto's real-time camera feed)
# ============================================================================
class MonitorCard(RoundedCard):
    """Displays what Pluto is currently 'seeing'. When connected and frames
    are arriving from video_client.py, renders the real camera stream;
    otherwise falls back to a 'NO SIGNAL' placeholder."""

    def __init__(self, parent, robot: "RobotCore" = None):
        super().__init__(parent)
        self.robot = robot
        self._frame_photo = None  # keep a reference so Tk doesn't GC it

        header = tk.Frame(self.body, bg=Theme.CARD)
        header.pack(
            fill="x",
            padx=12,
            pady=(6,2)
        )
        tk.Label(header, text="MONITOR", font=(Theme.FONT, 9, "bold"), bg=Theme.CARD,
                 fg=Theme.TEXT_SUB).pack(side="left")
        self.status_dot = tk.Canvas(header, width=9, height=9, bg=Theme.CARD,
                                     highlightthickness=0)
        self.status_dot.pack(side="right")
        self.status_dot.create_oval(1, 1, 8, 8, fill=Theme.BAD, outline="", tags="dot")
        self.status_label = tk.Label(header, text="SIMULATION FEED", font=(Theme.FONT, 8, "bold"),
                                      bg=Theme.CARD, fg=Theme.WARN)
        self.status_label.pack(side="right", padx=(0, 6))

        screen_wrap = tk.Frame(self.body, bg=Theme.CARD)
        screen_wrap.pack(
            fill="both",
            expand=True,
            padx=12,
            pady=(4,8)
        )
        self.screen = tk.Canvas(screen_wrap, bg="#05070b", highlightthickness=1,
                                 highlightbackground=Theme.BORDER)
        self.screen.pack(fill="both", expand=True)
        self.screen.bind("<Configure>", lambda e: self._draw_frame())

        self._tick = 0
        self.set_connected(False)
        self._animate()

    def set_connected(self, connected):
        color = Theme.GOOD if connected else Theme.BAD
        text = "LIVE" if connected else "SIMULATION FEED"
        self.status_dot.itemconfig("dot", fill=color)
        self.status_label.config(text=text, fg=(Theme.GOOD if connected else Theme.WARN))
        self._connected = connected

    def _draw_frame(self):
        """Render either the real camera frame (if video_client.py has one)
        or a 'NO SIGNAL' placeholder, with a CCTV-style OSD overlay
        (cam id, blinking REC dot, timestamp) drawn on top either way."""
        c = self.screen
        w = c.winfo_width()
        h = c.winfo_height()
        if w < 10 or h < 10:
            return
        c.delete("all")

        frame = self.robot.get_latest_frame() if self.robot else None

        if frame is not None and ImageTk is not None:
            # Fit the real frame to the canvas while preserving aspect ratio.
            fw, fh = frame.size
            scale = min(w / fw, h / fh)
            new_size = (max(1, int(fw * scale)), max(1, int(fh * scale)))
            resized = frame.resize(new_size)
            self._frame_photo = ImageTk.PhotoImage(resized)
            c.create_rectangle(0, 0, w, h, fill="#000000", outline="")
            c.create_image(w // 2, h // 2, image=self._frame_photo, anchor="center")
        else:
            # base picture area
            c.create_rectangle(0, 0, w, h, fill="#0b0f14", outline="")
            # faint horizontal scanlines -> analog-camera / CRT texture
            for y in range(0, h, 3):
                c.create_line(0, y, w, y, fill="#10151c")
            # light static/noise speckle, like a camera with no real signal yet
            for _ in range(90):
                x = random.randint(0, w)
                y = random.randint(0, h)
                sz = random.choice([1, 1, 2])
                shade = random.choice(["#1b222c", "#222a35", "#171d25"])
                c.create_rectangle(x, y, x + sz, y + sz, fill=shade, outline="")

        # thin vignette frame to sell a lens edge
        c.create_rectangle(0, 0, w, h, outline="#000000", width=3)

        # -- on-screen camera overlay (like a real CCTV OSD) -----------------
        c.create_text(12, 12, anchor="nw", text="CAM-01  \u2022  PLUTO",
                      fill=Theme.ACCENT, font=(Theme.FONT, 9, "bold"))

        if frame is not None and self._tick % 20 < 12:  # blinking REC indicator
            c.create_oval(w - 22, 12, w - 12, 22, fill=Theme.BAD, outline="")
            c.create_text(w - 28, 17, anchor="e", text="REC",
                          fill=Theme.BAD, font=(Theme.FONT, 9, "bold"))

        timestamp = datetime.datetime.now().strftime("%d-%m-%Y  %H:%M:%S")
        c.create_text(12, h - 12, anchor="sw", text=timestamp,
                      fill="#c7cfd8", font=("Consolas", 9))

        if frame is None:
            cx, cy = w / 2, h / 2
            c.create_text(cx, cy - 10, text="\U0001F4F9", font=(Theme.FONT, 26))
            c.create_text(cx, cy + 20, text="NO SIGNAL",
                          fill=Theme.TEXT_SUB, font=(Theme.FONT, 10, "bold"))
            c.create_text(cx, cy + 40, text="Connect to Pluto Core to view the live camera",
                          fill=Theme.TEXT_FAINT, font=(Theme.FONT, 8))

    def _animate(self):
        self._tick += 1
        self._draw_frame()
        self.after(150, self._animate)


# ============================================================================
#  SURROUNDING PARAMETERS CARD (environment sensors around the robot)
# ============================================================================
class ParamItem(tk.Frame):
    def __init__(self, parent, icon_fn, title):
        super().__init__(parent, bg=Theme.CARD)
        self.icon_fn = icon_fn
        row = tk.Frame(self, bg=Theme.CARD)
        row.pack(anchor="w")
        self.icon_canvas = tk.Canvas(row, width=22, height=22, bg=Theme.CARD, highlightthickness=0)
        self.icon_canvas.pack(side="left")
        tk.Label(row, text=title, font=(Theme.FONT, 9, "bold"), bg=Theme.CARD,
                 fg=Theme.TEXT_SUB).pack(side="left", padx=(6, 0))
        self.value_label = tk.Label(self, text="--", font=(Theme.FONT, 20, "bold"),
                                     bg=Theme.CARD, fg=Theme.TEXT_MAIN)
        self.value_label.pack(anchor="w", pady=(4, 0))
        self._draw_icon(Theme.ACCENT)

    def _draw_icon(self, color):
        self.icon_canvas.delete("all")
        self.icon_fn(self.icon_canvas, 11, 11, 18, color)

    def set_value(self, text, color=None):
        self.value_label.config(text=text, fg=color or Theme.TEXT_MAIN)
        self._draw_icon(color or Theme.ACCENT)


def icon_thermometer(canvas, cx, cy, s, color):
    w = s * 0.18
    top, bot = cy - s * 0.42, cy + s * 0.28
    canvas.create_line(cx, top, cx, bot, fill=color, width=w)
    canvas.create_oval(cx - s * 0.18, bot - s * 0.06, cx + s * 0.18, bot + s * 0.3,
                        fill=color, outline="")


def icon_droplet(canvas, cx, cy, s, color):
    pts = [cx, cy - s * 0.4, cx + s * 0.28, cy + s * 0.12, cx, cy + s * 0.4,
           cx - s * 0.28, cy + s * 0.12]
    canvas.create_polygon(pts, fill="", outline=color, width=2, smooth=True)


def icon_sun(canvas, cx, cy, s, color):
    r = s * 0.18
    canvas.create_oval(cx - r, cy - r, cx + r, cy + r, outline=color, width=2)
    for ang in range(0, 360, 45):
        rad = math.radians(ang)
        x1, y1 = cx + math.cos(rad) * r * 1.5, cy + math.sin(rad) * r * 1.5
        x2, y2 = cx + math.cos(rad) * r * 2.2, cy + math.sin(rad) * r * 2.2
        canvas.create_line(x1, y1, x2, y2, fill=color, width=2)


def icon_clock(canvas, cx, cy, s, color):
    r = s * 0.34
    canvas.create_oval(cx - r, cy - r, cx + r, cy + r, outline=color, width=2)
    canvas.create_line(cx, cy, cx, cy - r * 0.6, fill=color, width=2)
    canvas.create_line(cx, cy, cx + r * 0.42, cy + r * 0.18, fill=color, width=2)


def icon_network(canvas, cx, cy, s, color):
    r = s * 0.07
    top = (cx, cy - s * 0.3)
    left = (cx - s * 0.28, cy + s * 0.18)
    right = (cx + s * 0.28, cy + s * 0.18)
    canvas.create_line(*top, *left, fill=color, width=1.5)
    canvas.create_line(*top, *right, fill=color, width=1.5)
    canvas.create_line(*left, *right, fill=color, width=1.5)
    for (x, y) in (top, left, right):
        canvas.create_oval(x - r, y - r, x + r, y + r, fill=color, outline="")


def icon_gauge(canvas, cx, cy, s, color):
    r = s * 0.32
    canvas.create_arc(cx - r, cy - r, cx + r, cy + r, start=20, extent=140,
                       style="arc", outline=color, width=2)
    canvas.create_line(cx, cy, cx + r * 0.55, cy - r * 0.5, fill=color, width=2)
    canvas.create_oval(cx - 2, cy - 2, cx + 2, cy + 2, fill=color, outline="")


def icon_book(canvas, cx, cy, s, color):
    w, h = s * 0.28, s * 0.5
    canvas.create_line(cx, cy - h / 2, cx, cy + h / 2, fill=color, width=2)
    canvas.create_arc(cx - w * 2, cy - h / 2, cx, cy + h / 2, start=90, extent=-180,
                       style="arc", outline=color, width=2)
    canvas.create_arc(cx, cy - h / 2, cx + w * 2, cy + h / 2, start=90, extent=180,
                       style="arc", outline=color, width=2)


def icon_leaf(canvas, cx, cy, s, color):
    canvas.create_arc(cx - s * 0.3, cy - s * 0.3, cx + s * 0.3, cy + s * 0.3,
                       start=30, extent=250, style="arc", outline=color, width=2)
    canvas.create_line(cx - s * 0.05, cy - s * 0.05, cx + s * 0.16, cy + s * 0.16,
                        fill=color, width=2)


class SurroundingParamsCard(RoundedCard):
    def __init__(self, parent):
        super().__init__(parent, height=80)
        header = tk.Frame(self.body, bg=Theme.CARD)
        header.pack(fill="x", padx=18, pady=(10, 2))
        tk.Label(header, text="SURROUNDING PARAMETERS", font=(Theme.FONT, 10, "bold"),
                 bg=Theme.CARD, fg=Theme.TEXT_SUB).pack(side="left")
        tk.Label(header, text="  \u2022  from onboard sensors", font=(Theme.FONT, 9),
                 bg=Theme.CARD, fg=Theme.TEXT_FAINT).pack(side="left")

        grid = tk.Frame(self.body, bg=Theme.CARD)
        grid.pack(fill="both", expand=True, padx=18, pady=(2, 8))
        for i in range(4):
            grid.columnconfigure(i, weight=1, uniform="params")
        grid.rowconfigure(0, weight=1)

        self.temp_item = ParamItem(grid, icon_thermometer, "TEMPERATURE")
        self.humidity_item = ParamItem(grid, icon_droplet, "HUMIDITY")
        self.light_item = ParamItem(grid, icon_sun, "LIGHT INTENSITY")
        self.air_item = ParamItem(grid, icon_leaf, "AIR QUALITY")

        for i, item in enumerate([self.temp_item, self.humidity_item,
                                   self.light_item, self.air_item]):
            item.grid(
                row=0,
                column=i,
                sticky="nsew",
                padx=10
            )

    def refresh(self, robot: RobotCore):
        temp = robot.get_ambient_temperature_c()
        self.temp_item.set_value(f"{temp}\u00b0C", level_color(70, invert=False))

        hum = robot.get_humidity_percent()
        self.humidity_item.set_value(f"{hum}%", Theme.ACCENT)

        lux = robot.get_light_intensity_lux()
        self.light_item.set_value(f"{lux} lx", Theme.ACCENT)

        aqi = robot.get_air_quality_index()
        aqi_color = Theme.GOOD if aqi < 80 else (Theme.WARN if aqi < 150 else Theme.BAD)
        self.air_item.set_value(f"{aqi} AQI", aqi_color)


# ============================================================================
#  DATE & TIME CARD
# ============================================================================
class DateTimeCard(RoundedCard):
    def __init__(self, parent):
        super().__init__(parent, height=80)
        wrap = tk.Frame(self.body, bg=Theme.CARD)
        wrap.pack(
            fill="both",
            expand=True,
            padx=24,
            pady=10
        )
        tk.Label(wrap, text="DATE & TIME", font=(Theme.FONT, 10, "bold"), bg=Theme.CARD,
                 fg=Theme.TEXT_SUB).pack(anchor="w")
        self.time_label = tk.Label(wrap, text="--:--:--", font=(Theme.FONT, 26, "bold"),
                                    bg=Theme.CARD, fg=Theme.TEXT_MAIN)
        self.time_label.pack(anchor="w", pady=(6, 0))
        self.date_label = tk.Label(wrap, text="--", font=(Theme.FONT, 11),
                                    bg=Theme.CARD, fg=Theme.TEXT_SUB)
        self.date_label.pack(anchor="w")
        self._tick()

    def _tick(self):
        now = datetime.datetime.now()
        self.time_label.config(text=now.strftime("%H:%M:%S"))
        self.date_label.config(text=now.strftime("%A, %d %B %Y"))
        self.after(1000, self._tick)


# ============================================================================
#  DASHBOARD TAB
# ============================================================================
class DashboardFrame(tk.Frame):
    def __init__(self, parent, robot: RobotCore):
        super().__init__(parent, bg=Theme.BG)
        self.robot = robot

        # -- top strip: compact status boxes (Battery / Connectivity / --------
        # -- Memory / CPU) --------------------------------------------------
        strip = tk.Frame(self, bg=Theme.BG)
        strip.pack(fill="x", padx=28, pady=(10, 4))
        for i in range(4):
            strip.columnconfigure(i, weight=1, uniform="ministats")

        self.card_battery = MiniStatCard(strip, icon_battery, "BATTERY")
        self.card_connectivity = MiniStatCard(
            strip, lambda c, x, y, s, col: icon_signal(c, x, y, s, col, Theme.TRACK), "CONNECTIVITY")
        self.card_memory = MiniStatCard(strip, icon_chip, "MEMORY USED")
        self.card_cpu = MiniStatCard(strip, icon_cpu, "CPU LOAD")

        for i, card in enumerate([
            self.card_battery,
            self.card_connectivity,
            self.card_memory,
            self.card_cpu
        ]):
            card.grid(
                row=0,
                column=i,
                sticky="ew",
                padx=(0 if i == 0 else 10, 0),
                pady=0,
                ipady=2
            )

        # -- main body: Monitor (top-left) / Current Activity (top-right) / --
        # -- Surrounding Parameters (bottom-left) / Date & Time (bottom- -----
        # -- right). The bottom row height is pinned to the SAME fixed pixel
        # -- height as the top MiniStatCard strip (78px), and the Monitor /
        # -- Current Activity row absorbs all remaining space -- so the
        # -- layout always reads as: top strip ~10%, monitor/activity ~80%,
        # -- bottom row ~10% of the window height, and the bottom row is
        # -- always exactly as tall as the top strip. ------------------------
        body = tk.Frame(self, bg=Theme.BG)
        body.pack(fill="both", expand=True, padx=28, pady=(0, 10))

        # NOTE: the bottom row is pinned to a FIXED pixel height (matching the
        # top strip's MiniStatCard height of 78px, via height=78 passed into
        # SurroundingParamsCard / DateTimeCard's RoundedCard) rather than a
        # weighted fraction. Giving it weight=0 means it always sizes to its
        # fixed-height content, so it never stretches taller. The Monitor /
        # Current Activity block (row 0) gets all remaining flexible space,
        # which -- given the top strip and bottom block are each ~78px
        # (~10% of the 800px window) -- naturally works out to ~80% of the
        # screen height for the middle block, exactly as requested.
        body.columnconfigure(0, weight=1)
        body.rowconfigure(0, weight=6)    # Monitor + Activity
        body.rowconfigure(1, weight=2)    # Bottom panels

        top_block = tk.Frame(body, bg=Theme.BG)
        top_block.grid(
                row=0,
                column=0,
                sticky="nsew"
            )
        top_block.columnconfigure(0, weight=2)
        top_block.columnconfigure(1, weight=1)
        top_block.rowconfigure(0, weight=1)

        bottom_block = tk.Frame(body, bg=Theme.BG)
        bottom_block.grid(
            row=1,
            column=0,
            sticky="nsew",
            pady=(8,0)
        )
        bottom_block.columnconfigure(0, weight=2)
        bottom_block.columnconfigure(1, weight=1)
        bottom_block.rowconfigure(0, weight=1)

        # -- MONITOR (orange) -- the live feed canvas already fills 100% of
        # -- this card's body (see MonitorCard), so pinning the card itself
        # -- to the fixed top-block height makes the camera screen fill the
        # -- maximum available area of that region.
        self.monitor_card = MonitorCard(top_block, robot=self.robot)
        self.monitor_card.grid(row=0, column=0, sticky="nsew", padx=(0, 10))

        # -- CURRENT ACTIVITY (green) ----------------------------------------
        activity_card = RoundedCard(top_block)
        activity_card.grid(row=0, column=1, sticky="nsew", padx=(10, 0))
        ah = tk.Frame(activity_card.body, bg=Theme.CARD)
        ah.pack(fill="x", padx=18, pady=(16, 0))
        ic = tk.Canvas(ah, width=20, height=20, bg=Theme.CARD, highlightthickness=0)
        ic.pack(side="left")
        icon_bolt(ic, 10, 10, 20, Theme.ACCENT)
        tk.Label(ah, text="CURRENT ACTIVITY", font=(Theme.FONT, 10, "bold"), bg=Theme.CARD,
                 fg=Theme.TEXT_SUB).pack(side="left", padx=(8, 0))
        self.activity_label = tk.Label(activity_card.body, text="Idle",
                                        font=(Theme.FONT, 20, "bold"), wraplength=280,
                                        justify="left", bg=Theme.CARD, fg=Theme.ACCENT)
        self.activity_label.pack(
            anchor="nw",
            fill="both",
            expand=True,
            padx=18,
            pady=(12,18)
        )

        # -- SURROUNDING PARAMETERS (violet) ---------------------------------
        self.params_card = SurroundingParamsCard(bottom_block)
        self.params_card.grid(row=0, column=0, sticky="nsew", padx=(0, 10))

        # -- DATE & TIME (yellow) ---------------------------------------------
        self.datetime_card = DateTimeCard(bottom_block)
        self.datetime_card.grid(row=0, column=1, sticky="nsew", padx=(10, 0))

        self.refresh()

    def refresh(self):
        battery = self.robot.get_battery_percent()
        self.card_battery.set_value(f"{battery}%",
                                     "Charging" if battery < 40 else "Discharging",
                                     level_color(battery))

        network, state, kind = self.robot.get_connectivity()
        self.card_connectivity.set_value(network, f"{state}", status_color(kind))

        mem = self.robot.get_memory_percent()
        self.card_memory.set_value(f"{mem}%", "RAM in use", level_color(mem, invert=True))

        cpu = self.robot.get_cpu_percent()
        temp = self.robot.get_cpu_temp_c()
        self.card_cpu.set_value(f"{cpu}%", f"Temp: {temp}\u00b0C", level_color(cpu, invert=True))

        self.activity_label.config(text=self.robot.get_current_activity())
        self.monitor_card.set_connected(self.robot.get_live_feed_status())
        self.params_card.refresh(self.robot)

        self.after(2000, self.refresh)


# ============================================================================
#  OWNER REGISTRATION TAB
# ============================================================================
class OwnerRegistrationFrame(tk.Frame):
    def __init__(self, parent, robot: RobotCore):
        super().__init__(parent, bg=Theme.BG)
        self.robot = robot
        self.face_captured = False
        self.voice_captured = False
        self.face_path = None
        self.voice_path = None

        tk.Label(self, text="Register Owner", font=(Theme.FONT, 19, "bold"),
                 bg=Theme.BG, fg=Theme.TEXT_MAIN).pack(anchor="w", padx=28, pady=(22, 4))
        tk.Label(self, text="Enroll a person's name, date of birth, face sample, and voice "
                             "sample so the robot can recognize them later.",
                 font=(Theme.FONT, 10), bg=Theme.BG, fg=Theme.TEXT_SUB
                 ).pack(anchor="w", padx=28, pady=(0, 16))

        body = tk.Frame(self, bg=Theme.BG)
        body.pack(fill="both", expand=True, padx=28, pady=(0, 22))
        body.columnconfigure(0, weight=1)
        body.columnconfigure(1, weight=1)
        body.rowconfigure(0, weight=1)

        form_card = RoundedCard(body)
        form_card.grid(row=0, column=0, sticky="nsew", padx=(0, 10))
        form_panel = form_card.body
        pad = {"padx": 20, "pady": (12, 0)}

        def section_label(text):
            tk.Label(form_panel, text=text, font=(Theme.FONT, 10, "bold"),
                     bg=Theme.CARD, fg=Theme.TEXT_SUB).pack(anchor="w", **pad)

        section_label("FULL NAME")
        self.name_entry = tk.Entry(form_panel, font=(Theme.FONT, 12), bg=Theme.TRACK,
                                    fg=Theme.TEXT_MAIN, insertbackground=Theme.TEXT_MAIN,
                                    relief="flat", highlightthickness=1,
                                    highlightbackground=Theme.BORDER,
                                    highlightcolor=Theme.ACCENT)
        self.name_entry.pack(fill="x", padx=20, pady=(6, 0), ipady=7)

        section_label("DATE OF BIRTH")
        dob_row = tk.Frame(form_panel, bg=Theme.CARD)
        dob_row.pack(fill="x", padx=20, pady=(6, 0))
        this_year = datetime.date.today().year
        self.day_cb = ttk.Combobox(dob_row, values=[f"{d:02d}" for d in range(1, 32)],
                                    width=4, state="readonly")
        self.month_cb = ttk.Combobox(dob_row, values=[
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
        ], width=5, state="readonly")
        self.year_cb = ttk.Combobox(dob_row, values=[str(y) for y in range(this_year - 100, this_year + 1)],
                                     width=6, state="readonly")
        self.day_cb.pack(side="left")
        self.month_cb.pack(side="left", padx=6)
        self.year_cb.pack(side="left")

        section_label("FACE SAMPLE")
        face_row = tk.Frame(form_panel, bg=Theme.CARD)
        face_row.pack(fill="x", padx=20, pady=(8, 0))
        self.face_canvas = tk.Canvas(face_row, width=64, height=64, bg=Theme.TRACK,
                                      highlightthickness=1, highlightbackground=Theme.BORDER)
        self.face_canvas.pack(side="left")
        self._draw_face_placeholder()
        face_btns = tk.Frame(face_row, bg=Theme.CARD)
        face_btns.pack(side="left", padx=14)
        self.face_status_label = tk.Label(face_btns, text="No face captured yet",
                                           font=(Theme.FONT, 9), bg=Theme.CARD, fg=Theme.TEXT_SUB)
        self.face_status_label.pack(anchor="w")
        self.capture_face_btn = self._make_button(face_btns, "Capture Face (Camera)", self.capture_face)
        self.capture_face_btn.pack(anchor="w", pady=(6, 0))

        section_label("SPEECH SAMPLE")
        voice_row = tk.Frame(form_panel, bg=Theme.CARD)
        voice_row.pack(fill="x", padx=20, pady=(8, 0))
        self.voice_canvas = tk.Canvas(voice_row, width=140, height=48, bg=Theme.TRACK,
                                       highlightthickness=1, highlightbackground=Theme.BORDER)
        self.voice_canvas.pack(side="left")
        self._draw_voice_placeholder()
        voice_btns = tk.Frame(voice_row, bg=Theme.CARD)
        voice_btns.pack(side="left", padx=14)
        self.voice_status_label = tk.Label(voice_btns, text="No voice sample recorded",
                                            font=(Theme.FONT, 9), bg=Theme.CARD, fg=Theme.TEXT_SUB)
        self.voice_status_label.pack(anchor="w")
        self.record_voice_btn = self._make_button(voice_btns, "Record Voice Sample", self.capture_voice)
        self.record_voice_btn.pack(anchor="w", pady=(6, 0))

        btn_row = tk.Frame(form_panel, bg=Theme.CARD)
        btn_row.pack(fill="x", padx=20, pady=22)
        self.save_btn = tk.Button(btn_row, text="Save Owner", command=self.save_owner, bg=Theme.GOOD,
                                   fg="#04220f", relief="flat", font=(Theme.FONT, 11, "bold"),
                                   activebackground=Theme.GOOD, cursor="hand2", padx=18, pady=8, bd=0)
        self.save_btn.pack(side="left")
        self.clear_btn = tk.Button(btn_row, text="Clear Form", command=self.clear_form, bg=Theme.TRACK,
                                    fg=Theme.TEXT_MAIN, relief="flat", font=(Theme.FONT, 11),
                                    activebackground=Theme.TRACK, cursor="hand2", padx=18, pady=8, bd=0)
        self.clear_btn.pack(side="left", padx=(10, 0))

        list_card = RoundedCard(body)
        list_card.grid(row=0, column=1, sticky="nsew", padx=(10, 0))
        list_panel = list_card.body
        tk.Label(list_panel, text="REGISTERED OWNERS", font=(Theme.FONT, 10, "bold"),
                 bg=Theme.CARD, fg=Theme.TEXT_SUB).pack(anchor="w", padx=20, pady=(16, 8))

        style = ttk.Style()
        style.configure("Owners.Treeview", background=Theme.TRACK, fieldbackground=Theme.TRACK,
                         foreground=Theme.TEXT_MAIN, rowheight=30, borderwidth=0, font=(Theme.FONT, 10))
        style.configure("Owners.Treeview.Heading", background=Theme.CARD, foreground=Theme.TEXT_SUB,
                         font=(Theme.FONT, 9, "bold"), relief="flat")
        style.map("Owners.Treeview", background=[("selected", Theme.ACCENT_DIM)],
                  foreground=[("selected", Theme.ACCENT)])

        cols = ("name", "dob", "face", "voice", "registered")
        self.tree = ttk.Treeview(list_panel, columns=cols, show="headings", style="Owners.Treeview")
        headings = {"name": "Name", "dob": "DOB", "face": "Face", "voice": "Voice",
                    "registered": "Registered On"}
        widths = {"name": 130, "dob": 90, "face": 55, "voice": 55, "registered": 110}
        for c in cols:
            self.tree.heading(c, text=headings[c])
            self.tree.column(c, width=widths[c], anchor="center" if c != "name" else "w")
        self.tree.pack(fill="both", expand=True, padx=20, pady=(0, 18))

        # populate from Pluto's pluto.db (via GET /owners), not a local file
        self.refresh_owners()

    def refresh_owners(self):
        """
        Reloads the Registered Owners table from Pluto's real database:
            GET /owners  ->  OwnerManager.list_owners()  ->  pluto.db
        This is the single source of truth for registered owners -- there
        is no local owners.json anymore. If Pluto isn't reachable yet, the
        table is simply left as-is (or empty on first load).
        """
        for item in self.tree.get_children():
            self.tree.delete(item)

        if not (self.robot and self.robot.api):
            return

        try:
            result = self.robot.api.list_owners()
        except PlutoAPIClientError:
            return

        owners = result.get("owners", []) if isinstance(result, dict) else []
        # newest first, matching registered_at (ISO, sortable as string)
        for record in sorted(owners, key=lambda r: r.get("registered_at", ""), reverse=True):
            registered_at = record.get("registered_at", "")
            # server stores ISO 'YYYY-MM-DDTHH:MM:SS'; show just the date part
            registered_display = registered_at.split("T")[0] if registered_at else ""
            self.tree.insert("", "end", values=(
                record.get("name", ""),
                record.get("dob", ""),
                "\u2713" if record.get("face_files") else "\u2717",
                "\u2713" if record.get("voice_files") else "\u2717",
                registered_display,
            ))

    def _make_button(self, parent, text, command):
        btn = tk.Button(parent, text=text, command=command, bg=Theme.ACCENT, fg="#052622",
                         relief="flat", font=(Theme.FONT, 9, "bold"), activebackground=Theme.ACCENT_2,
                         cursor="hand2", bd=0, padx=10, pady=6)
        btn.bind("<Enter>", lambda e: btn.config(bg=Theme.ACCENT_2, fg="#ffffff"))
        btn.bind("<Leave>", lambda e: btn.config(bg=Theme.ACCENT, fg="#052622"))
        return btn

    def _draw_face_placeholder(self, captured=False):
        c = self.face_canvas
        c.delete("all")
        color = Theme.GOOD if captured else Theme.TEXT_SUB
        icon_person(c, 32, 30, 56, color)

    def _draw_voice_placeholder(self, captured=False):
        c = self.voice_canvas
        c.delete("all")
        color = Theme.GOOD if captured else Theme.TEXT_SUB
        bars = 16
        w = 140 / bars
        for i in range(bars):
            h = random.randint(8, 36) if captured else 5 + int(9 * abs(math.sin(i * 0.7)))
            x0 = i * w + 3
            c.create_rectangle(x0, 24 - h / 2, x0 + w - 4, 24 + h / 2, fill=color, outline="")

    def _set_busy(self, busy):
        """Disable/enable the interactive buttons while a capture is running."""
        state = "disabled" if busy else "normal"
        for btn in (self.capture_face_btn, self.record_voice_btn, self.save_btn, self.clear_btn):
            btn.config(state=state)

    # -- FACE CAPTURE (real camera, via face_capture.py) -----------------------
    def capture_face(self):
        if face_capture is None:
            messagebox.showerror(
                "Camera Module Not Available",
                "face_capture.py could not import its camera dependency.\n\n"
                f"Details: {FACE_MODULE_ERROR}\n\n"
                "Install it with:\n    pip install opencv-python"
            )
            return

        name = self.name_entry.get().strip() or "owner"
        self.face_status_label.config(text="Opening camera... look at the preview window",
                                       fg=Theme.WARN)
        self._set_busy(True)

        def worker():
            try:
                path = face_capture.capture_face(owner_name=name)
                error = None
            except Exception as e:  # camera/hardware errors surface here
                path = None
                error = str(e)
            # hop back onto the Tkinter main thread to touch any widgets
            self.after(0, lambda: self._on_face_captured(path, error))

        threading.Thread(target=worker, daemon=True).start()

    def _on_face_captured(self, path, error):
        self._set_busy(False)
        if path:
            self.face_path = path
            self.face_captured = True
            self._show_face_thumbnail(path)
            self.face_status_label.config(text=f"Face captured: {os.path.basename(path)}",
                                           fg=Theme.GOOD)
        else:
            self.face_captured = False
            self._draw_face_placeholder(captured=False)
            self.face_status_label.config(text="Face capture failed / cancelled", fg=Theme.BAD)
            if error:
                messagebox.showerror("Face Capture Failed",
                                      f"Could not capture a face.\n\n{error}")
            else:
                messagebox.showwarning("Face Capture Cancelled",
                                        "No image was captured. Make sure a webcam is connected "
                                        "and try again (press ESC in the preview window to cancel).")

    def _show_face_thumbnail(self, path):
        try:
            img = tk.PhotoImage(file=path)
            factor_x = max(1, img.width() // 64)
            factor_y = max(1, img.height() // 64)
            img = img.subsample(factor_x, factor_y)
            self._face_img_ref = img  # keep a reference so it isn't garbage-collected
            self.face_canvas.delete("all")
            self.face_canvas.create_image(32, 32, image=img)
        except tk.TclError:
            # PNG couldn't be loaded directly (older Tk); fall back to the icon
            self._draw_face_placeholder(captured=True)

    # -- VOICE CAPTURE (real microphone, via voice_capture.py) -----------------
    def capture_voice(self):
        if voice_capture is None:
            messagebox.showerror(
                "Microphone Module Not Available",
                "voice_capture.py could not import its audio dependency.\n\n"
                f"Details: {VOICE_MODULE_ERROR}\n\n"
                "Install it with:\n    pip install pyaudio\n"
                "(On Raspberry Pi / Debian you may first need:\n"
                "    sudo apt-get install portaudio19-dev)"
            )
            return

        name = self.name_entry.get().strip() or "owner"
        duration = 4
        self.voice_status_label.config(text=f"Recording... speak now ({duration}s)", fg=Theme.WARN)
        self._set_busy(True)

        def on_progress(elapsed, total):
            remaining = max(0, int(total - elapsed) + 1)
            self.after(0, lambda: self.voice_status_label.config(
                text=f"Recording... {remaining}s left", fg=Theme.WARN))

        def worker():
            try:
                path = voice_capture.record_voice(owner_name=name, duration=duration,
                                                   progress_callback=on_progress)
                error = None
            except Exception as e:
                path = None
                error = str(e)
            self.after(0, lambda: self._on_voice_captured(path, error))

        threading.Thread(target=worker, daemon=True).start()

    def _on_voice_captured(self, path, error):
        self._set_busy(False)
        if path:
            self.voice_path = path
            self.voice_captured = True
            self._draw_voice_waveform(path)
            self.voice_status_label.config(text=f"Voice recorded: {os.path.basename(path)}",
                                            fg=Theme.GOOD)
        else:
            self.voice_captured = False
            self._draw_voice_placeholder(captured=False)
            self.voice_status_label.config(text="Voice recording failed", fg=Theme.BAD)
            if error:
                messagebox.showerror("Voice Recording Failed",
                                      f"Could not record audio.\n\n{error}")
            else:
                messagebox.showwarning("Voice Recording Failed",
                                        "No audio was recorded. Make sure a microphone is "
                                        "connected and try again.")

    def _draw_voice_waveform(self, path):
        """Draw a real (downsampled) waveform from the recorded WAV file."""
        c = self.voice_canvas
        c.delete("all")
        bars = 16
        amplitudes = [10] * bars
        if AUDIOOP_AVAILABLE:
            try:
                with wave.open(path, "rb") as wf:
                    n_frames = wf.getnframes()
                    sampwidth = wf.getsampwidth()
                    chunk = max(1, n_frames // bars)
                    for i in range(bars):
                        data = wf.readframes(chunk)
                        if not data:
                            amplitudes[i] = 2
                            continue
                        rms = audioop.rms(data, sampwidth)
                        amplitudes[i] = rms
            except (wave.Error, OSError):
                pass
        max_amp = max(amplitudes) or 1
        for i, amp in enumerate(amplitudes):
            h = 4 + (amp / max_amp) * 34
            w = 140 / bars
            x0 = i * w + 3
            c.create_rectangle(x0, 24 - h / 2, x0 + w - 4, 24 + h / 2, fill=Theme.GOOD, outline="")

    def clear_form(self):
        self.name_entry.delete(0, tk.END)
        self.day_cb.set("")
        self.month_cb.set("")
        self.year_cb.set("")
        self.face_captured = False
        self.voice_captured = False
        self.face_path = None
        self.voice_path = None
        self._draw_face_placeholder(captured=False)
        self._draw_voice_placeholder(captured=False)
        self.face_status_label.config(text="No face captured yet", fg=Theme.TEXT_SUB)
        self.voice_status_label.config(text="No voice sample recorded", fg=Theme.TEXT_SUB)

    def save_owner(self):
        name = self.name_entry.get().strip()
        if not name:
            messagebox.showwarning("Missing Name", "Please enter the owner's full name.")
            return
        if not (self.day_cb.get() and self.month_cb.get() and self.year_cb.get()):
            messagebox.showwarning("Missing DOB", "Please select the full date of birth.")
            return

        dob = f"{self.day_cb.get()}-{self.month_cb.get()}-{self.year_cb.get()}"
        record = {
            "name": name,
            "dob": dob,
            "face_captured": self.face_captured,
            "face_path": self.face_path,
            "voice_captured": self.voice_captured,
            "voice_path": self.voice_path,
        }

        enrolled = self.robot.register_owner(record)  # sends face/voice to Pluto

        if enrolled:
            # Pluto's pluto.db is the only source of truth -- reload the
            # table from GET /owners instead of inserting a local copy.
            self.refresh_owners()
            messagebox.showinfo(
                "Owner Saved",
                f"{name} has been enrolled on Pluto for face/voice recognition."
            )
            self.clear_form()
        else:
            error = getattr(self.robot, "last_error", None)
            messagebox.showwarning(
                "Not Enrolled on Pluto",
                f"{name} could not be enrolled on Pluto.\n\n{error or 'Pluto is not reachable.'}\n\n"
                "Connect to Pluto Core and try saving again."
            )


# ============================================================================
#  MEMORY CORE TAB
# ============================================================================
class MemoryTypeCard(RoundedCard):
    """One card representing a single memory subsystem: shows its purpose,
    a storage-usage bar, and a scrollable list of what is currently stored
    inside it."""

    def __init__(self, parent, icon_fn, accent, on_open=None):
        super().__init__(parent)
        self.icon_fn = icon_fn
        self.accent = accent
        self.on_open = on_open
        self._data = None

        header = tk.Frame(self.body, bg=Theme.CARD)
        header.pack(fill="x", padx=18, pady=(14, 0))
        self.icon_canvas = tk.Canvas(header, width=22, height=22, bg=Theme.CARD,
                                      highlightthickness=0)
        self.icon_canvas.pack(side="left")
        self.icon_fn(self.icon_canvas, 11, 11, 20, accent)
        self.title_label = tk.Label(header, text="", font=(Theme.FONT, 12, "bold"),
                                     bg=Theme.CARD, fg=Theme.TEXT_MAIN)
        self.title_label.pack(side="left", padx=(8, 0))
        self.pct_label = tk.Label(header, text="", font=(Theme.FONT, 10, "bold"),
                                   bg=Theme.CARD, fg=accent)
        self.pct_label.pack(side="right")

        self.purpose_label = tk.Label(self.body, text="", font=(Theme.FONT, 9),
                                       bg=Theme.CARD, fg=Theme.TEXT_SUB, justify="left",
                                       wraplength=340)
        self.purpose_label.pack(fill="x", padx=18, pady=(6, 8), anchor="w")

        self.view_hint = tk.Label(self.body, text="Click to view full details \u2192",
                                   font=(Theme.FONT, 8, "bold"), bg=Theme.CARD, fg=accent)
        self.view_hint.pack(fill="x", padx=18, pady=(0, 4), anchor="w")

        bar_wrap = tk.Frame(self.body, bg=Theme.CARD)
        bar_wrap.pack(fill="x", padx=18, pady=(0, 4))
        self.bar_canvas = tk.Canvas(bar_wrap, height=8, bg=Theme.TRACK, highlightthickness=0)
        self.bar_canvas.pack(fill="x")
        self.bar_canvas.bind("<Configure>", lambda e: self._redraw_bar())

        self.storage_label = tk.Label(self.body, text="", font=(Theme.FONT, 8),
                                       bg=Theme.CARD, fg=Theme.TEXT_FAINT)
        self.storage_label.pack(fill="x", padx=18, pady=(3, 8), anchor="w")

        tk.Frame(self.body, bg=Theme.BORDER, height=1).pack(fill="x", padx=18)

        entries_header = tk.Frame(self.body, bg=Theme.CARD)
        entries_header.pack(fill="x", padx=18, pady=(8, 2))
        self.entries_title = tk.Label(entries_header, text="STORED ENTRIES",
                                       font=(Theme.FONT, 9, "bold"), bg=Theme.CARD,
                                       fg=Theme.TEXT_SUB)
        self.entries_title.pack(side="left")

        list_wrap = tk.Frame(self.body, bg=Theme.CARD)
        list_wrap.pack(fill="both", expand=True, padx=18, pady=(2, 14))

        self.text = tk.Text(list_wrap, bg=Theme.CARD, fg=Theme.TEXT_MAIN, bd=0,
                             highlightthickness=0, wrap="word", font=(Theme.FONT, 9),
                             cursor="arrow", state="disabled")
        scroll = tk.Scrollbar(list_wrap, command=self.text.yview, troughcolor=Theme.CARD,
                              bg=Theme.TRACK)
        self.text.configure(yscrollcommand=scroll.set)
        scroll.pack(side="right", fill="y")
        self.text.pack(side="left", fill="both", expand=True)

        self.text.tag_configure("entry_title", font=(Theme.FONT, 9, "bold"),
                                 foreground=Theme.TEXT_MAIN)
        self.text.tag_configure("entry_detail", font=(Theme.FONT, 9),
                                 foreground=Theme.TEXT_SUB)
        self.text.tag_configure("entry_ts", font=(Theme.FONT, 8), foreground=Theme.TEXT_FAINT)
        self.text.configure(cursor="hand2")
        self.text.bind("<Button-1>", lambda e: (self._handle_click(), "break"))

        self._pct = 0

        # -- make the whole card clickable to open the full detail popup --
        clickable_widgets = [
            self.canvas, self.body, header, self.icon_canvas, self.title_label,
            self.pct_label, self.purpose_label, self.view_hint, bar_wrap,
            self.storage_label, entries_header, self.entries_title,
        ]
        for w in clickable_widgets:
            w.configure(cursor="hand2")
            w.bind("<Button-1>", self._handle_click)

    def _handle_click(self, event=None):
        if self.on_open and self._data is not None:
            self.on_open(self._data)

    def _redraw_bar(self):
        c = self.bar_canvas
        w = c.winfo_width()
        h = c.winfo_height()
        if w < 4 or h < 2:
            return
        c.delete("all")
        c.create_rectangle(0, 0, w, h, fill=Theme.TRACK, outline="")
        fill_w = max(3, w * (self._pct / 100))
        c.create_rectangle(0, 0, fill_w, h, fill=self.accent, outline="")

    def set_data(self, data):
        self._data = data
        self.title_label.config(text=data["title"].upper())
        self.purpose_label.config(text=data.get("short_desc", data["purpose"]))

        used = data["used_mb"]
        total = data["total_mb"]
        pct = min(100, (used / total) * 100) if total else 0
        self._pct = pct
        self._redraw_bar()
        self.pct_label.config(text=f"{pct:.0f}%")
        self.storage_label.config(
            text=f"{used:.2f} MB used of {total} MB allocated")

        entries = data["entries"]
        self.entries_title.config(text=f"STORED ENTRIES ({len(entries)})")

        self.text.config(state="normal")
        self.text.delete("1.0", "end")
        for i, (title, detail, ts) in enumerate(entries):
            self.text.insert("end", f"\u2022 {title}\n", "entry_title")
            self.text.insert("end", f"   {detail}\n", "entry_detail")
            self.text.insert("end", f"   {ts}\n", "entry_ts")
            if i < len(entries) - 1:
                self.text.insert("end", "\n")
        self.text.config(state="disabled")


class MemoryDetailPopup(tk.Toplevel):
    """A popup window shown when a memory card is clicked. Displays the
    full purpose description, storage usage, and every stored entry with
    its timestamp for that particular memory subsystem."""

    def __init__(self, parent, accent):
        super().__init__(parent)
        self.accent = accent
        self.configure(bg=Theme.BG)
        self.geometry("620x560")
        self.minsize(480, 420)
        self.transient(parent)

        # -- header --------------------------------------------------------
        header = tk.Frame(self, bg=Theme.BG)
        header.pack(fill="x", padx=26, pady=(22, 6))
        self.title_label = tk.Label(header, text="", font=(Theme.FONT, 17, "bold"),
                                     bg=Theme.BG, fg=Theme.TEXT_MAIN)
        self.title_label.pack(side="left")
        self.pct_label = tk.Label(header, text="", font=(Theme.FONT, 12, "bold"),
                                   bg=Theme.BG, fg=accent)
        self.pct_label.pack(side="right")

        close_btn = tk.Button(header, text="\u2715", relief="flat", bd=0, cursor="hand2",
                               font=(Theme.FONT, 11, "bold"), bg=Theme.BG, fg=Theme.TEXT_SUB,
                               activebackground=Theme.BG, activeforeground=Theme.TEXT_MAIN,
                               command=self.destroy)
        close_btn.pack(side="right", padx=(0, 14))

        self.purpose_label = tk.Label(self, text="", font=(Theme.FONT, 10), bg=Theme.BG,
                                       fg=Theme.TEXT_SUB, justify="left", wraplength=560)
        self.purpose_label.pack(fill="x", padx=26, pady=(0, 12), anchor="w")

        bar_wrap = tk.Frame(self, bg=Theme.BG)
        bar_wrap.pack(fill="x", padx=26, pady=(0, 4))
        self.bar_canvas = tk.Canvas(bar_wrap, height=10, bg=Theme.TRACK, highlightthickness=0)
        self.bar_canvas.pack(fill="x")
        self.bar_canvas.bind("<Configure>", lambda e: self._redraw_bar())

        self.storage_label = tk.Label(self, text="", font=(Theme.FONT, 9), bg=Theme.BG,
                                       fg=Theme.TEXT_FAINT)
        self.storage_label.pack(fill="x", padx=26, pady=(4, 14), anchor="w")

        tk.Frame(self, bg=Theme.BORDER, height=1).pack(fill="x", padx=26)

        entries_header = tk.Frame(self, bg=Theme.BG)
        entries_header.pack(fill="x", padx=26, pady=(14, 6))
        self.entries_title = tk.Label(entries_header, text="STORED ENTRIES",
                                       font=(Theme.FONT, 10, "bold"), bg=Theme.BG,
                                       fg=Theme.TEXT_SUB)
        self.entries_title.pack(side="left")

        card = RoundedCard(self)
        card.pack(fill="both", expand=True, padx=26, pady=(0, 24))

        list_wrap = tk.Frame(card.body, bg=Theme.CARD)
        list_wrap.pack(fill="both", expand=True, padx=6, pady=6)

        self.text = tk.Text(list_wrap, bg=Theme.CARD, fg=Theme.TEXT_MAIN, bd=0,
                             highlightthickness=0, wrap="word", font=(Theme.FONT, 10),
                             cursor="arrow", state="disabled", padx=10, pady=10)
        scroll = tk.Scrollbar(list_wrap, command=self.text.yview, troughcolor=Theme.CARD,
                              bg=Theme.TRACK)
        self.text.configure(yscrollcommand=scroll.set)
        scroll.pack(side="right", fill="y")
        self.text.pack(side="left", fill="both", expand=True)

        self.text.tag_configure("entry_title", font=(Theme.FONT, 10, "bold"),
                                 foreground=Theme.TEXT_MAIN)
        self.text.tag_configure("entry_detail", font=(Theme.FONT, 10),
                                 foreground=Theme.TEXT_SUB)
        self.text.tag_configure("entry_ts", font=(Theme.FONT, 9), foreground=accent)

        self._pct = 0

    def _redraw_bar(self):
        c = self.bar_canvas
        w = c.winfo_width()
        h = c.winfo_height()
        if w < 4 or h < 2:
            return
        c.delete("all")
        c.create_rectangle(0, 0, w, h, fill=Theme.TRACK, outline="")
        fill_w = max(3, w * (self._pct / 100))
        c.create_rectangle(0, 0, fill_w, h, fill=self.accent, outline="")

    def set_data(self, data):
        self.title(data["title"])
        self.title_label.config(text=data["title"])
        self.purpose_label.config(text=data["purpose"])

        used = data["used_mb"]
        total = data["total_mb"]
        pct = min(100, (used / total) * 100) if total else 0
        self._pct = pct
        self._redraw_bar()
        self.pct_label.config(text=f"{pct:.0f}%")
        self.storage_label.config(text=f"{used:.2f} MB used of {total} MB allocated")

        entries = data["entries"]
        self.entries_title.config(text=f"STORED ENTRIES ({len(entries)})")

        self.text.config(state="normal")
        self.text.delete("1.0", "end")
        for i, (title, detail, ts) in enumerate(entries):
            self.text.insert("end", f"\u2022 {title}\n", "entry_title")
            self.text.insert("end", f"   {detail}\n", "entry_detail")
            self.text.insert("end", f"   Recorded at {ts}\n", "entry_ts")
            if i < len(entries) - 1:
                self.text.insert("end", "\n")
        self.text.config(state="disabled")


class MemoryCoreFrame(tk.Frame):
    """Shows the four memory subsystems from Pluto's architecture: Short
    Term, Semantic, Behavioral, and Episodic memory -- what each one is
    for, how much storage it is using, and what is currently stored in it."""

    def __init__(self, parent, robot: RobotCore):
        super().__init__(parent, bg=Theme.BG)
        self.robot = robot

        tk.Label(self, text="Memory Core", font=(Theme.FONT, 19, "bold"),
                 bg=Theme.BG, fg=Theme.TEXT_MAIN).pack(anchor="w", padx=28, pady=(22, 4))
        tk.Label(self, text="A breakdown of Pluto's four memory subsystems \u2014 what each "
                             "one is for, how full it is, and what's currently stored inside.",
                 font=(Theme.FONT, 10), bg=Theme.BG, fg=Theme.TEXT_SUB
                 ).pack(anchor="w", padx=28, pady=(0, 16))

        grid = tk.Frame(self, bg=Theme.BG)
        grid.pack(fill="both", expand=True, padx=28, pady=(0, 22))
        grid.columnconfigure(0, weight=1, uniform="mem")
        grid.columnconfigure(1, weight=1, uniform="mem")
        grid.rowconfigure(0, weight=1, uniform="mem")
        grid.rowconfigure(1, weight=1, uniform="mem")

        self.short_term_card = MemoryTypeCard(grid, icon_clock, Theme.ACCENT,
                                               on_open=lambda d: self._open_detail(d, Theme.ACCENT))
        self.semantic_card = MemoryTypeCard(grid, icon_network, Theme.ACCENT_2,
                                             on_open=lambda d: self._open_detail(d, Theme.ACCENT_2))
        self.behavioral_card = MemoryTypeCard(grid, icon_gauge, Theme.WARN,
                                               on_open=lambda d: self._open_detail(d, Theme.WARN))
        self.episodic_card = MemoryTypeCard(grid, icon_book, Theme.GOOD,
                                             on_open=lambda d: self._open_detail(d, Theme.GOOD))
        self._detail_popup = None

        self.short_term_card.grid(row=0, column=0, sticky="nsew", padx=(0, 10), pady=(0, 10))
        self.semantic_card.grid(row=0, column=1, sticky="nsew", padx=(10, 0), pady=(0, 10))
        self.behavioral_card.grid(row=1, column=0, sticky="nsew", padx=(0, 10), pady=(10, 0))
        self.episodic_card.grid(row=1, column=1, sticky="nsew", padx=(10, 0), pady=(10, 0))

        self.refresh()

    def _open_detail(self, data, accent):
        if self._detail_popup is not None and self._detail_popup.winfo_exists():
            self._detail_popup.destroy()
        popup = MemoryDetailPopup(self.winfo_toplevel(), accent)
        popup.set_data(data)
        self._detail_popup = popup
        popup.grab_set()
        popup.focus_set()

    def refresh(self):
        data = self.robot.get_memory_core_data()
        self.short_term_card.set_data(data["short_term"])
        self.semantic_card.set_data(data["semantic"])
        self.behavioral_card.set_data(data["behavioral"])
        self.episodic_card.set_data(data["episodic"])

        self.after(4000, self.refresh)


# ============================================================================
#  MAIN APPLICATION
# ============================================================================
class RobotDashboardApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Pluto Control Dashboard")
        self.geometry("1280x800")
        self.minsize(1020, 660)
        self.configure(bg=Theme.BG)

        self.robot = RobotCore()

        self._setup_style()
        self._build_sidebar()
        self.right_container = tk.Frame(self, bg=Theme.BG)
        self.right_container.pack(side="right", fill="both", expand=True)
        self._build_content()

        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _setup_style(self):
        style = ttk.Style(self)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass
        style.configure("TCombobox", fieldbackground=Theme.TRACK, background=Theme.TRACK,
                         foreground=Theme.TEXT_MAIN, arrowcolor=Theme.TEXT_SUB)

    def _build_sidebar(self):
        self.sidebar = tk.Frame(self, bg=Theme.BG_SIDEBAR, width=210)
        self.sidebar.pack(side="left", fill="y")
        self.sidebar.pack_propagate(False)

        brand = tk.Frame(self.sidebar, bg=Theme.BG_SIDEBAR)
        brand.pack(fill="x", pady=(28, 26))
        logo_canvas = tk.Canvas(brand, width=56, height=56, bg=Theme.BG_SIDEBAR, highlightthickness=0)
        logo_canvas.pack()
        icon_robot_head(logo_canvas, 28, 30, 44, Theme.ACCENT)
        tk.Label(brand, text="PLUTO", font=(Theme.FONT, 13, "bold"), bg=Theme.BG_SIDEBAR,
                 fg=Theme.TEXT_MAIN).pack(pady=(10, 0))
        

        tk.Frame(self.sidebar, bg=Theme.BORDER, height=1).pack(fill="x", padx=18, pady=(0, 16))

        self.nav_buttons = {}
        self.nav_indicators = {}
        nav_items = [("dashboard", "Dashboard"), ("memory", "Memory Core"),
                     ("owners", "Register Owner")]
        for key, label in nav_items:
            row = tk.Frame(self.sidebar, bg=Theme.BG_SIDEBAR, cursor="hand2")
            row.pack(fill="x", padx=10, pady=3)
            indicator = tk.Frame(row, bg=Theme.BG_SIDEBAR, width=3)
            indicator.pack(side="left", fill="y")
            lbl = tk.Label(row, text=label, anchor="w", font=(Theme.FONT, 11), bg=Theme.BG_SIDEBAR,
                           fg=Theme.TEXT_SUB, padx=14, pady=10)
            lbl.pack(side="left", fill="x", expand=True)
            for widget in (row, lbl):
                widget.bind("<Button-1>", lambda e, k=key: self.show_frame(k))
                widget.bind("<Enter>", lambda e, k=key: self._hover_nav(k, True))
                widget.bind("<Leave>", lambda e, k=key: self._hover_nav(k, False))
            self.nav_buttons[key] = (row, lbl)
            self.nav_indicators[key] = indicator

        tk.Frame(self.sidebar, bg=Theme.BG_SIDEBAR).pack(fill="both", expand=True)

        connect_btn = tk.Button(self.sidebar, text="\u26a1  Connect to Pluto Core",
                                 anchor="center", relief="flat", font=(Theme.FONT, 10, "bold"),
                                 bg=Theme.ACCENT, fg="#052622", activebackground=Theme.ACCENT_2,
                                 bd=0, padx=14, pady=11, cursor="hand2", command=self.attempt_connect)
        connect_btn.pack(fill="x", padx=14, pady=(2, 18), side="bottom")
        connect_btn.bind("<Enter>", lambda e: connect_btn.config(bg=Theme.ACCENT_2, fg="#ffffff"))
        connect_btn.bind("<Leave>", lambda e: connect_btn.config(bg=Theme.ACCENT, fg="#052622"))

    def _hover_nav(self, key, entering):
        row, lbl = self.nav_buttons[key]
        if self._current_frame == key:
            return
        color = "#161d27" if entering else Theme.BG_SIDEBAR
        row.config(bg=color)
        lbl.config(bg=color)

    def _build_content(self):
        self.pages_container = tk.Frame(self.right_container, bg=Theme.BG)
        self.pages_container.pack(fill="both", expand=True)

        self.frames = {
            "dashboard": DashboardFrame(self.pages_container, self.robot),
            "memory": MemoryCoreFrame(self.pages_container, self.robot),
            "owners": OwnerRegistrationFrame(self.pages_container, self.robot),
        }
        for frame in self.frames.values():
            frame.place(relx=0, rely=0, relwidth=1, relheight=1)

        self._current_frame = None
        self.show_frame("dashboard")

    def show_frame(self, key):
        self._current_frame = key
        self.frames[key].tkraise()
        for k, (row, lbl) in self.nav_buttons.items():
            active = k == key
            bg = Theme.ACCENT_DIM if active else Theme.BG_SIDEBAR
            fg = Theme.ACCENT if active else Theme.TEXT_SUB
            row.config(bg=bg)
            lbl.config(bg=bg, fg=fg)
            self.nav_indicators[k].config(bg=Theme.ACCENT if active else Theme.BG_SIDEBAR)

    def attempt_connect(self):
        """Connects to Pluto: checks the FastAPI health endpoint and starts
        the telemetry + camera WebSocket clients (which keep retrying in
        the background even if Pluto isn't reachable yet)."""
        if PlutoAPIClient is None:
            messagebox.showerror(
                "API Client Unavailable",
                f"api_client.py could not be imported.\n\nDetails: {API_CLIENT_ERROR}\n\n"
                "Install it with:\n    pip install requests"
            )
            return
        if PlutoWebSocketClient is None or PlutoVideoClient is None:
            messagebox.showerror(
                "WebSocket Client Unavailable",
                "websocket_client.py / video_client.py could not be imported.\n\n"
                f"Details: {WS_CLIENT_ERROR or VIDEO_CLIENT_ERROR}\n\n"
                "Install it with:\n    pip install websocket-client pillow"
            )
            return

        ok = self.robot.connect()
        if ok:
            messagebox.showinfo(
                "Connected",
                f"Connected to Pluto's FastAPI server at "
                f"{self.robot.host}:{self.robot.api_port}.\n\n"
                f"Telemetry and camera WebSocket clients are now running and "
                f"will keep reconnecting automatically if the link drops."
            )
        else:
            messagebox.showwarning(
                "Cannot Reach Pluto",
                f"Could not reach Pluto's FastAPI server at "
                f"{self.robot.host}:{self.robot.api_port}.\n\n"
                "Make sure Pluto is powered on, server.py is running, and "
                "this device is on the same network. The telemetry/camera "
                "clients will keep retrying in the background and will pick "
                "up automatically once Pluto comes online."
            )

    def _on_close(self):
        self.robot.disconnect()
        self.destroy()


if __name__ == "__main__":
    app = RobotDashboardApp()
    app.mainloop()
